# .upptimerc.yml

# Il proprietario (tu) e il nome del repository.
owner: atrisorb
repo: atrisorb.github.io

# Elenco dei siti da monitorare. Ho aggiunto sia il sito principale che l'API.
sites:
  - name: Erasmus Housing
    url: https://www.erasmus-housing.com
  - name: Erasmus Housing API
    url: https://api.erasmus-housing.com

# Configurazione della pagina di status
status-website:
  # L'URL base dove verrà pubblicata la pagina
  baseUrl: /
  # Logo, titolo e descrizione che appariranno sulla pagina
  logoUrl: https://www.erasmus-housing.com/web-app-manifest-512x512.png
  name: Erasmus Housing Status
  introTitle: "Stato dei servizi di Erasmus Housing"
  introMessage: "Questa pagina mostra in tempo reale lo stato di salute del nostro sito e dei servizi associati. In caso di disservizi, troverai qui tutti gli aggiornamenti."
  
  # --- PERSONALIZZAZIONE DELLO STILE ---
  # Qui diciamo a Upptime di caricare un nostro file CSS personalizzato.
  customStylesheets:
    - /assets/styles.css # Nota: il file sorgente sarà .scss, ma Jekyll lo compila in .css

# Assegna le "issues" di GitHub a te quando un servizio va offline
assignees:
  - atrisorb

workflowSchedule:
  uptime: '*/5 * * * *' # Controlla i siti ogni 5 minuti
