owner: atrisorb
repo: erasmus-housing-status-page

sites:
  - name: Erasmus Housing Website
    url: https://www.erasmus-housing.com
  - name: Erasmus Housing API
    url: https://api.erasmus-housing.com/health/database
  - name: Image Storage Service
    url: https://api.erasmus-housing.com/health/storage
  - name: Email Service (Resend)
    url: https://api.erasmus-housing.com/health/email
  - name: Maps API (Google)
    url: https://api.erasmus-housing.com/health/maps
  - name: Payment Services (Stripe)
    url: https://api.erasmus-housing.com/health/payments
  - name: Exchange Rates API
    url: https://api.erasmus-housing.com/health/exchange-rates
  - name: Notifications (Telegram)
    url: https://api.erasmus-housing.com/health/telegram
  - name: Notifications (Discord)
    url: https://api.erasmus-housing.com/health/discord

status-website:
  baseUrl: /erasmus-housing-status-page
  logoUrl: https://www.erasmus-housing.com/web-app-manifest-512x512.png
  name: Erasmus Housing Status
  
  # --- INIZIO MODIFICHE PER LA LINGUA INGLESE ---
  introTitle: "Erasmus Housing Service Status"
  introMessage: "This page provides real-time status updates for our website and associated services. If there are any interruptions, all updates will be posted here."
  
  # Aggiungiamo il blocco di internazionalizzazione per tradurre l'interfaccia
  i18n:
    en:
      activeIncidents: Active Incidents
      allSystemsOperational: All systems operational
      incidentReport: "Incident #{incidentId} report"
      activeIncidentSummary: "An incident is currently ongoing for {siteName}."
      degradedPerformance: Degraded Performance
      completeOutage: Complete Outage
      partialOutage: Partial Outage
      pastIncidents: Past Incidents
      incidentHistory: Incident History
      incidents: Incidents
      incident: Incident
      uptime: Uptime
      response_time: Response Time
      resolved: Resolved
      inProgress: In Progress
      investigating: Investigating
      identified: Identified
      monitoring: Monitoring
      history: History
  # --- FINE MODIFICHE PER LA LINGUA INGLESE ---

  customHeadHtml: |
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
    <style>
      body { font-family: 'Inter', sans-serif !important; }
      header .img-fluid { max-height: 70px !important; width: auto !important; }
      :root { --green: #F37F21 !important; }
      header.container { background: #F37F21 !important; color: white !important; }
      header.container h1, header.container p, header.container a { color: white !important; }
      header.container a:hover { color: #ffd4b0 !important; }
      .dot.--up { background: #F37F21 !important; }
      .chart-container .recharts-wrapper .recharts-surface .recharts-area-area path {
          fill: rgba(243, 127, 33, 0.2) !important;
          stroke: rgba(243, 127, 33, 0.5) !important;
      }
    </style>

assignees:
  - atrisorb

workflowSchedule:
  uptime: '*/5 * * * *'
